apiVersion: v1
kind: Pod
metadata:
  name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op0-{{ .Values.operator.op0.device.hostname }}
spec:
  containers:
  - name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op0-{{ .Values.operator.op0.device.hostname }}
    image: wakeup706/tensorflow-scale:{{ .Values.operator.op0.device.type }}-master-1.1
    resources:
      requests:
        memory: "{{ .Values.operator.op0.resource.mem }}M"
        cpu: "{{ .Values.operator.op0.resource.cpu }}m"
    ports:
    - containerPort: {{ .Values.operator.op0.port }}
      hostPort: {{ .Values.operator.op0.port }}
    command: ["/bin/bash","-c","python worker.py --worker_hosts={{ .Values.operator.op0.ip }}:{{ .Values.operator.op0.port }},{{ .Values.operator.op1.ip }}:{{ .Values.operator.op1.port }},{{ .Values.operator.op2.ip }}:{{ .Values.operator.op2.port }},{{ .Values.operator.op3.ip }}:{{ .Values.operator.op3.port }},{{ .Values.operator.op4.ip }}:{{ .Values.operator.op4.port }} --job_name=worker --task_index=0& python scale.py"]
    securityContext:
      privileged: true
    env:
    - name : MASTER_IP
      value: {{ .Values.operator.op0.ip }}
    - name : MASTER_PORT
      value: "{{ .Values.operator.op0.port }}"
    - name : BROKER
      value: {{ .Values.mqtt.brokerIP }}
    - name : TOPIC
      value: {{ .Values.mqtt.topic }}
    - name : PERIOD
      value: "{{ .Values.period }}"
    - name : REQUEST
      value: "{{ .Values.name.request }}"
    - name : OP0
      value: "0"
    - name : OP1
      value: "1"
    - name : OP2
      value: "2"
    - name : OP3
      value: "3"
    - name : OP4
      value: "4"
  nodeSelector:
    device: "{{ .Values.operator.op0.device.label }}"
