apiVersion: v1
kind: Pod
metadata:
  name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op1
spec:
  containers:
  - name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op1
    image: wakeup706/tensorflow-yolo:{{ .Values.operator.op1.device.type }}-worker
    ports:
    - containerPort: {{ .Values.operator.op1.port }}
      hostPort: {{ .Values.operator.op1.port }}
    command: ["/bin/bash","-c","python worker.py --worker_hosts={{ .Values.operator.op0.ip }}:{{ .Values.operator.op0.port }},{{ .Values.operator.op1.ip }}:{{ .Values.operator.op1.port }},{{ .Values.operator.op2.ip }}:{{ .Values.operator.op2.port }} --job_name=worker --task_index=1"]
    securityContext:
      privileged: true
  nodeSelector:
    device: "{{ .Values.operator.op1.device.label }}"

------

apiVersion: v1
kind: Pod
metadata:
  name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op2
spec:
  containers:
  - name: req{{ .Values.name.request }}-app{{ .Values.name.application }}-op2
    image: wakeup706/tensorflow-yolo:{{ .Values.operator.op2.device.type }}-worker
    ports:
    - containerPort: {{ .Values.operator.op2.port }}
      hostPort: {{ .Values.operator.op2.port }}
    command: ["/bin/bash","-c","python worker.py --worker_hosts={{ .Values.operator.op0.ip }}:{{ .Values.operator.op0.port }},{{ .Values.operator.op1.ip }}:{{ .Values.operator.op1.port }},{{ .Values.operator.op2.ip }}:{{ .Values.operator.op2.port }} --job_name=worker --task_index=2"]
    securityContext:
      privileged: true
  nodeSelector:
    device: "{{ .Values.operator.op2.device.label }}"
